### ISSUE TITLE
Clicking on the Logo Should Redirect to Homepage

### ISSUE THREAD

**Issue by ElsarChabaev** [remsfal/remsfal-frontend#307] opened 2024-11-26 12:58 UTC
### Description

Currently, clicking on the application logo does not redirect the user to the homepage. This behavior is unintuitive, as users generally expect the logo in web applications to serve as a shortcut to return to the main page.

### Motivation

Improving the user experience is crucial for retaining and engaging users. Redirecting to the homepage when the logo is clicked is a widely recognized standard in web applications.

### Details

Current Behavior:

Clicking the logo currently does nothing 

Expected Behavior:

When a user clicks on the application logo, they should be redirected to the homepage 

Implementation Steps:

Ensure the logo is wrapped in a clickable anchor (<a> tag).
Set the anchor’s href attribute to the homepage URL.

**Comment by astanik** [comment] 2024-11-27 16:05
Duplicate of #208 and #203

**Closed by astanik** 2024-11-27 16:05 UTC
